version: "3.8"

services:
  application:
    build: .
    environment:
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: UrlShortenerDb
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - mssqlserver:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: $DB_PASSWORD
volumes:
  mssqlserver: